services:
  - type: web
    name: hypd-url-shortener
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: BASE_URL
        value: https://hypd-url-shortener.onrender.com
      - key: DATABASE_URL
        value: postgresql://postgres.jggyeiywgyuwdiogyxrm:hypd-url-shortener@aws-0-ap-south-1.pooler.supabase.com:6543/postgres
      - key: API_VERSION
        value: v1
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: DEFAULT_EXPIRY_DAYS
        value: 30
      - key: SHORT_URL_LENGTH
        value: 6
      - key: HYPD_BASE_URL
        value: https://www.hypd.store
